pre-commit:
  parallel: true
  jobs:
    - name: prettier
      run: npx prettier --write --cache --ignore-unknown {staged_files}
      stage_fixed: true

pre-push:
  piped: true
  jobs:
    - run: npm install

    - name: lint
      group:
        parallel: true
        jobs:
          - name: prettier
            run: npx prettier --check .
          - name: tsc
            run: npm run tsc

post-merge:
  only:
    - ref: main
  commands:
    npm-install:
      run: npm install --ignore-scripts

output:
  - summary
  - failure
