REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM httpobsapi;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM httpobsapi;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM httpobsapi;
DROP USER httpobsapi;