name: Stage build

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to build (default: main)"
        required: false
        default: refs/heads/main

permissions: {}

jobs:
  build:
    if: github.repository_owner == 'mdn' && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      environment: staging
      ref: ${{ inputs.ref }}
